Setting view update
Kalatco/SmallTalk pull request #22
Opened 2020-10-31 23:12 UTC by kansairob

Changed layout of the login page and colors. Also worked on the functionality for the registration page.

2020-10-31 23:24 UTC, Kalatco requested changes

2020-10-31 23:24 UTC, Kalatco commented on package-lock.json
> +  "requires": true,
this file doesn't belong to our project, remove it

2020-10-31 23:24 UTC, Kalatco commented on smallTalk/settings.py
> +ALLOWED_HOSTS = ['0.0.0.0', '192.168.0.107', '172.30.41.76', '192.168.1.48']
change to ALLOWED_HOSTS = ['*']

2020-10-31 23:24 UTC, Kalatco commented on src/views/LoginView.js
> +  const [isLoginForm, setIsLoginForm] = useState(true);
the purpose of git version control is to separate different changes (or tasks) of code into separate branches. Your task to "update settings page" has nothing to do with the login form, please remove these changes and move them to a new branch

2020-10-31 23:24 UTC, Kalatco commented on src/views/SettingsView.js
>    const handleFirstNameInput = (enteredText) => {
we talked a few days ago about removing these functions and directly calling the useState setter method for all these cases. please fix

2020-10-31 23:24 UTC, Kalatco commented on smallTalk/settings.py
> +ALLOWED_HOSTS = ['0.0.0.0', '192.168.0.107', '172.30.41.76', '192.168.1.48']
this will allow any host computer to serve data from the server

2020-10-31 23:24 UTC, Kalatco commented on package-lock.json
> +  "requires": true,
but do not remove the /src/package-lock.json file

2020-10-31 23:32 UTC, kansairob commented on package-lock.json
> +  "requires": true,
Updated file.

2020-10-31 23:35 UTC, kansairob commented on smallTalk/settings.py
> +ALLOWED_HOSTS = ['0.0.0.0', '192.168.0.107', '172.30.41.76', '192.168.1.48']
Updated file.

2020-11-01 00:04 UTC, kansairob commented on src/views/LoginView.js
> +  const [isLoginForm, setIsLoginForm] = useState(true);
Updated file.

2020-11-02 06:39 UTC, kansairob commented on src/views/SettingsView.js
>    const handleFirstNameInput = (enteredText) => {
Updated file.

2020-11-02 17:48 UTC, Kalatco requested changes

2020-11-02 17:48 UTC, Kalatco commented on src/store/index.js
> +const SERVER_ADDRESS = '192.168.1.48';
theres a merge conflict, change the IP to '192.168.0.107:8080'

2020-11-02 17:48 UTC, Kalatco commented on src/views/LoginView.js
> +  const [emailReg, setEmailReg] = usestate("");
the login view registration code is here again???

2020-11-02 17:48 UTC, Kalatco commented on src/views/SettingsView.js
>    const handleFirstNameInput = (enteredText) => {
issue still exists

2020-11-03 03:33 UTC, kansairob commented on src/store/index.js
> +const SERVER_ADDRESS = '192.168.1.48';
Fixed

2020-11-03 03:33 UTC, kansairob commented on src/views/LoginView.js
> +  const [emailReg, setEmailReg] = usestate("");
Fixed

2020-11-04 05:29 UTC, merged