More settings functionality
Kalatco/SmallTalk pull request #33
Opened 2020-11-17 00:44 UTC by KazyManazy

Added add user text field to SettingsView and added the axios put request in the SetingsView.  Also updated the api routing for adding a user to user the username instead of userID

2020-11-17 03:02 UTC, Kalatco requested changes

2020-11-17 03:02 UTC, Kalatco commented on src/views/SettingsView.js
> +                      value={newUserText}
an easy fix is to just get rid of this line: vale={newUserText}

2020-11-17 03:02 UTC, Kalatco commented on src/views/SettingsView.js
> +                onPress={() => changeChat(item2.username)}>
changeChat() is undefined

2020-11-17 03:03 UTC, Kalatco commented
@KazyManazy we want to keep the /src/package-lock.json file but  we do not want to keep  /package-lock.json.

2020-11-17 03:09 UTC, Kalatco commented on src/views/SettingsView.js
> +                      value={newUserText}
but we will only be able to use 1 input box at a time, which is fine for now.

2020-11-19 23:38 UTC, KazyManazy commented on src/views/SettingsView.js
> +                onPress={() => changeChat(item2.username)}>
No idea how that even got in there. Not my code, I'll chuck it.

2020-11-19 23:41 UTC, KazyManazy commented on src/views/SettingsView.js
> +                      value={newUserText}
I think I might just leave this in for now, because I can't think of any other way to add the ability to add members to multiple groups. It won't affect who's added to the group since the correct add group button must be pressed.

2020-11-20 22:19 UTC, Kalatco requested changes

2020-11-20 22:19 UTC, Kalatco commented on src/store/index.js
> +const SERVER_ADDRESS = '192.168.1.7:8000';
can you fix this again, another thing with git, it might be better to only "git add" the files you want added to the pull request.

2020-11-20 22:38 UTC, Kalatco requested changes

2020-11-20 22:38 UTC, Kalatco commented on src/views/SettingsView.js
> +  const addUser = (group_id) => {
When we want to add a new user, we want to somehow let the user know, we can use the react native Alert() object for this.

Also, we need to clear the text input after a new user was added.

If the put request fails with a 400 error, we need to let them know it failed using a .catch()

```
axios.put( )
.then(() => {
    Alert ...
})
.catch(error => {
    Alert.alert(
        "Add user failed",
        "Username not found"
    );
});
```

something like this

2020-11-20 22:38 UTC, Kalatco commented on src/views/SettingsView.js
> +  const deleteUser = (group_id, user_id) => {
Same thing as addUser comment

2020-11-20 22:38 UTC, Kalatco commented on src/views/SettingsView.js
> +    axios.put(url, update_parameters, {
same thing as adduser comment

2020-11-20 22:38 UTC, Kalatco commented on src/views/ChatSelectionView.js
> +    axios.put(url, update_parameters, {
same thing as adduser comment

2020-11-20 22:38 UTC, Kalatco commented on src/views/ChatSelectionView.js
> +    axios.put(url, update_parameters, {
a cleaner way to build the API url would be to do:
```
axios.put(`${props.serverName}/api/groups/${group_id}/addchat`)
```

2020-11-20 22:38 UTC, Kalatco commented on src/views/ChatSelectionView.js
> +    axios.put(url, update_parameters, {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2020-11-20 22:38 UTC, Kalatco commented on src/views/ChatSelectionView.js
> +    axios.put(url, update_parameters, {
Also please fix all other URL strings for the settingView file

2020-11-20 22:38 UTC, Kalatco commented on messenger/views.py
> +        return Response({'response': 'Invalid access permissions for this content'})
add status=status.HTTP_400_BAD_REQUEST

2020-11-20 22:38 UTC, Kalatco commented on messenger/views.py
> +        return Response({'response': 'Invalid access permissions for this content'})
add status=status.HTTP_400_BAD_REQUEST

2020-11-20 22:38 UTC, Kalatco commented on messenger/views.py
> +        return Response({'response': 'Invalid access permissions for this content'})
add status=status.HTTP_400_BAD_REQUEST

2020-11-20 22:38 UTC, Kalatco commented on messenger/views.py
> +        return Response({'response': 'Invalid access permissions for this content'})
add status=status.HTTP_400_BAD_REQUEST

2020-11-20 22:38 UTC, Kalatco commented on messenger/views.py
> +        return Response({'response': 'Invalid access permissions for this content'})
add status=status.HTTP_400_BAD_REQUEST

2020-11-20 22:43 UTC, Kalatco requested changes

2020-11-20 22:43 UTC, Kalatco commented on messenger/views.py
> +        return Response({"Group does not exist"}, status=status.HTTP_400_BAD_REQUEST)
since we are returning JSON, all the responses need to be similar to eachother, such as on line 144.

In that case our return will look like this:
```
Response({'response': 'Group does not exist'}, ...)
```

And when the error is captured on the app frontend, we can then pass this error you defined to the user by doing:
```
.catch(error => {
     Alert.alert(
          'Add user error',
         error.response
    );
});
```

2020-11-20 22:54 UTC, Kalatco commented on src/views/ChatSelectionView.js
> +    axios.put(url, update_parameters, {
Instead of using the update_parameters variable, it would be better to do
```
axios.put(url, { 'chat_name': newChatText }, ...
```
This way, we can avoid declaring a variable that is used only once.

2020-11-22 17:24 UTC, KazyManazy commented on src/views/SettingsView.js
> +  const addUser = (group_id) => {
The then and catch statements never really seem to occur whenever I run my code.  I added them pretty much exactly as you added them I can't get them to run.

2020-11-22 17:35 UTC, KazyManazy commented on src/views/SettingsView.js
> +  const addUser = (group_id) => {
Never mine, got it working, just dont have the refresh working.

2020-11-23 01:30 UTC, Kalatco approved these changes
looks good

2020-11-23 01:32 UTC, merged